spring:
  application:
    name: order-service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: ${Kafka_host}:9092
    user-name: ${Kafka_name}
    password: ${Kafka_password}



server:
  port: 19093


eureka:
  client:
    service-url:
      defaultZone: http://${Eureka_name}:${Eureka_password}@${Eureka_host}:19090/eureka/

kafka:
  event:
    group: order_group
    name:
      order-create: order-topic
      product_decrease: product_decrease
